name: Create Release

on:
  workflow_dispatch:

env:
  VSIX_NAME: 'embedd-peripheral-viewer'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      is_prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check prerelease status
        id: check_prerelease
        run: |
          if [[ "${{ steps.get_version.outputs.version }}" == *"-rc"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npx vsce package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: ./*.vsix
          retention-days: 7

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          path: artifacts

      - name: Read changelog
        id: changelog_release
        uses: embedd-actions/read_changelog_action@v3
        with:
          changelogfile: 'CHANGELOG.md'
          tag: ${{ needs.build.outputs.version }}

      - name: Prepare release notes
        env:
          REL_CHANGES: ${{ steps.changelog_release.outputs.content }}
        run: |
          echo "## [${{ needs.build.outputs.version }}] - $(date +'%Y-%m-%d')" >> Release_Notes.md
          echo "" >> Release_Notes.md
          echo "$REL_CHANGES" >> Release_Notes.md

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "Release_Notes.md"
          allowUpdates: false
          prerelease: ${{ needs.build.outputs.is_prerelease }}
          tag: "v${{ needs.build.outputs.version }}"
          commit: ${{ github.ref_name }}
          artifacts: "artifacts/*.vsix"
          artifactContentType: application/octet-stream

  publish-open-vsx:
    name: Open VSX Registry
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.is_prerelease == 'false'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          path: artifacts

      - name: Publish to Open VSX
        run: npx ovsx publish artifacts/*.vsix -p ${{ secrets.OPEN_VSX_TOKEN }}

  publish-vscode-marketplace:
    name: VS Code Marketplace
    needs: build
    runs-on: ubuntu-latest
    # if: needs.build.outputs.is_prerelease == 'false'
    if: false # Temporarily disable publishing to VS Code Marketplace
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vsix-package
          path: artifacts

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --packagePath artifacts/*.vsix
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
